# Generated by Django 2.2.5 on 2022-05-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(help_text='标签序号', verbose_name='标签序号')),
                ('type_name', models.CharField(help_text='电影标签', max_length=20, verbose_name='电影标签')),
            ],
            options={
                'verbose_name': '电影标签',
                'db_table': 'tb_movie_type',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Studio_id', models.CharField(help_text='演播厅id', max_length=20, verbose_name='演播厅id')),
                ('Studio_name', models.CharField(help_text='演播厅名称', max_length=20, verbose_name='演播厅名称')),
                ('Studio_type', models.CharField(help_text='演播厅类型', max_length=20, verbose_name='演播厅类型')),
                ('Seating', models.CharField(help_text='座位个数', max_length=20, verbose_name='座位个数')),
            ],
            options={
                'verbose_name': '演播厅',
                'db_table': 'tb_Studio',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seat_id', models.IntegerField(help_text='座位id', max_length=20, verbose_name='座位id')),
                ('Seat_name', models.CharField(help_text='座位编号', max_length=20, verbose_name='座位编号')),
                ('s_stu', models.ManyToManyField(to='administer.Studio')),
            ],
            options={
                'verbose_name': '座位',
                'db_table': 'tb_Seat',
            },
        ),
    ]
